# Generated by Django 4.2.6 on 2023-10-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surfsession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
                ('spot', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
            ],
        ),
    ]
